object Versions {

    const val lifecycleVersion = "2.4.0-alpha03"
    const val lifecycleExtensionVersion = "2.2.0"
    const val roomVersion = "2.4.0"
    const val gradleVersion = "4.1.3"
    const val kotlinVersion = "1.5.20"
    const val coreKtxVersion = "1.3.2"
    const val appCompatVersion = "1.3.1"
    const val materialVersion = "1.3.0"
    const val constraintLayoutVersion = "2.0.4"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val junit4Version = "4.13.2"
    const val junit5Version = "5.8.1"
    const val junitExtensionsVersion = "1.1.2"
    const val espressoCoreVersion = "3.3.0"
    const val workManager = "2.5.0"
    const val navigationVersion = "2.4.0-alpha07"
    const val retrofitVersion = "2.9.0"
    const val loggingInterceptor = "4.9.0"
    const val okHttpVersion = "4.9.1"
    const val coilVersion = "1.2.1"
    const val androidArchCoreTest = "2.1.0"
    const val coroutinesVersion = "1.6.4"
    const val daggerVersion = "2.40.5"
    const val fragmentVersion = "1.5.2"
    const val lottieVersion = "3.4.0"
    const val timberVersion = "5.0.1"
    const val recyclerview = "1.2.1"
    const val mockito_version = "3.8.0"
}